<?php

namespace Database\Seeders;

use App\Models\PlanoConta;
use Illuminate\Database\Seeder;

class PlanoContaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        PlanoConta::firstOrCreate(['id'=>1, 	'pai_id'=>NULL, 	'codigo'=> '1', 				'conta'=> 'ATIVO', 									'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>2, 	'pai_id'=>1, 		'codigo'=> '1.1', 				'conta'=> 'CIRCULANTE', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>3, 	'pai_id'=>2, 		'codigo'=> '1.1.1', 			'conta'=> 'DISPONIVEL', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>4, 	'pai_id'=>3, 		'codigo'=> '1.1.1.001', 		'conta'=> 'CAIXA', 									'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>5, 	'pai_id'=>4, 		'codigo'=> '1.1.1.001.0001', 	'conta'=> 'Caixa', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>7, 	'pai_id'=>3, 		'codigo'=> '1.1.1.002', 		'conta'=> 'BANCOS C/ MOVIMENTO', 						'alias'=> 'banco', 				'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>9, 	'pai_id'=>2, 		'codigo'=> '1.1.2', 			'conta'=> 'CLIENTES', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>10, 	'pai_id'=>9, 		'codigo'=> '1.1.2.001', 		'conta'=> 'CLIENTES A RECEBER', 						'alias'=> 'cliente_receber', 		'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>13, 	'pai_id'=>9, 		'codigo'=> '1.1.2.002', 		'conta'=> 'CHEQUES A RECEBER', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>15, 	'pai_id'=>2, 		'codigo'=> '1.1.3', 			'conta'=> 'OUTROS CRÉDITOS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>16, 	'pai_id'=>15, 	'codigo'=> '1.1.3.001', 		'conta'=> 'BANCOS C/ VINCULADA', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>17, 	'pai_id'=>15, 	'codigo'=> '1.1.3.005', 		'conta'=> 'TITULOS A RECUPERAR', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>18, 	'pai_id'=>17, 	'codigo'=> '1.1.3.005.0001', 	'conta'=> 'Simples Nacional a Recuperar', 			'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>19, 	'pai_id'=>2, 		'codigo'=> '1.1.4', 			'conta'=> 'APLICACOES FINANCEIRAS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>20, 	'pai_id'=>19, 	'codigo'=> '1.1.4.001', 		'conta'=> 'APLICACOES FINANCEIRAS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>21, 	'pai_id'=>2, 		'codigo'=> '1.1.5', 			'conta'=> 'ESTOQUE', 									'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>22, 	'pai_id'=>21, 	'codigo'=> '1.1.5.001', 		'conta'=> 'MERCADORAS E PRODUTOS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>23, 	'pai_id'=>22, 	'codigo'=> '1.1.5.001.0001', 	'conta'=> 'Mercadorias p/ Revenda', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>24, 	'pai_id'=>21, 	'codigo'=> '1.1.5.002', 		'conta'=> 'ALMOFARIFADO', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>25, 	'pai_id'=>24, 	'codigo'=> '1.1.5.002.0001', 	'conta'=> 'Mercadorias', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>26, 	'pai_id'=>21, 	'codigo'=> '1.1.5.003', 		'conta'=> '(-) PROVISAO P/ AJUSTE DE ESTOQUE', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>27, 	'pai_id'=>26, 	'codigo'=> '1.1.5.003.0001', 	'conta'=> '(-) Ajuste de Estoque', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>28, 	'pai_id'=>2, 		'codigo'=> '1.1.6', 			'conta'=> 'DESPESAS PAGAS ANTECIPADAMENTE', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>29, 	'pai_id'=>28, 	'codigo'=> '1.1.6.001', 		'conta'=> 'DESPESAS MESES SEGUINTES', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>30, 	'pai_id'=>29, 	'codigo'=> '1.1.6.001.0001', 	'conta'=> 'Assinaturas e Anuidades', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>31, 	'pai_id'=>1, 		'codigo'=> '1.2', 				'conta'=> 'NAO-CIRCULANTE', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>32, 	'pai_id'=>31, 	'codigo'=> '1.2.1', 			'conta'=> 'REALIZAVEL A LONGO PRAZO', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>33, 	'pai_id'=>32, 	'codigo'=> '1.2.1.001', 		'conta'=> 'CLIENTES', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>34, 	'pai_id'=>32, 	'codigo'=> '1.2.1.002', 		'conta'=> 'OUTROS CREDITOS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>35, 	'pai_id'=>31, 	'codigo'=> '1.2.2', 			'conta'=> 'INVESTIMENTOS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>36, 	'pai_id'=>35, 	'codigo'=> '1.2.2.001', 		'conta'=> 'IMOVEIS NAO-DESTINADOS AO USO', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>37, 	'pai_id'=>35, 	'codigo'=> '1.2.2.002', 		'conta'=> '(-) PROVISAO P/ PERDAS PERMANENTES', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>38, 	'pai_id'=>37, 	'codigo'=> '1.2.2.002.0001', 	'conta'=> '(-) Equipamentos e Patrimonio', 			'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>39, 	'pai_id'=>31, 	'codigo'=> '1.2.3', 			'conta'=> 'IMOBILIZADO', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>40, 	'pai_id'=>39, 	'codigo'=> '1.2.3.001', 		'conta'=> 'IMOVEIS', 									'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>41, 	'pai_id'=>40, 	'codigo'=> '1.2.3.001.0001', 	'conta'=> 'Terrenos', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>42, 	'pai_id'=>40, 	'codigo'=> '1.2.3.001.0002', 	'conta'=> 'Construções', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>43, 	'pai_id'=>40, 	'codigo'=> '1.2.3.001.0003', 	'conta'=> 'Edificios', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>44, 	'pai_id'=>39, 	'codigo'=> '1.2.3.002', 		'conta'=> 'COMPUTADORES E PERIFÉRICOS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>45, 	'pai_id'=>44, 	'codigo'=> '1.2.3.002.0001', 	'conta'=> 'COMPUTADORES', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>46, 	'pai_id'=>39, 	'codigo'=> '1.2.3.003', 		'conta'=> 'MAQUINAS E EQUIPAMENTOS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>47, 	'pai_id'=>46, 	'codigo'=> '1.2.3.003.0001', 	'conta'=> 'Maquinas e Equipamentos', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>48, 	'pai_id'=>39, 	'codigo'=> '1.2.3.004', 		'conta'=> 'VEICULOS', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>49, 	'pai_id'=>48, 	'codigo'=> '1.2.3.004.0001', 	'conta'=> 'Veiculos', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>50, 	'pai_id'=>39, 	'codigo'=> '1.2.3.005 (-) ', 	'conta'=> 'DEPRECIACOES/AMORTIZACOES', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>51, 	'pai_id'=>50, 	'codigo'=> '1.2.3.005.0001', 	'conta'=> '(-) Edificios', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>52, 	'pai_id'=>50, 	'codigo'=> '1.2.3.005.0002', 	'conta'=> '(-) Moveis e Utensilios', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>53, 	'pai_id'=>50, 	'codigo'=> '1.2.3.005.0003', 	'conta'=> '(-) Maquinas e Equipamentos', 				'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>54, 	'pai_id'=>50, 	'codigo'=> '1.2.3.005.0004', 	'conta'=> '(-) Veiculos', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>55, 	'pai_id'=>31, 	'codigo'=> '1.2.4', 			'conta'=> 'INTANGIVEL', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>56, 	'pai_id'=>55, 	'codigo'=> '1.2.4.001', 		'conta'=> 'MARCAS E PATENTES', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>57, 	'pai_id'=>NULL, 	'codigo'=> '2', 				'conta'=> 'PASSIVO', 									'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>58, 	'pai_id'=>57, 	'codigo'=> '2.1', 				'conta'=> 'CIRCULANTE', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>59, 	'pai_id'=>58, 	'codigo'=> '2.1.1', 			'conta'=> 'EMPRESTIMOS E FINANCIAMENTOS', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>60, 	'pai_id'=>59, 	'codigo'=> '2.1.1.001', 		'conta'=> 'EMPRESTIMOS', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>61, 	'pai_id'=>59, 	'codigo'=> '2.1.1.002', 		'conta'=> 'FINANCIAMENTOS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>62, 	'pai_id'=>58, 	'codigo'=> '2.1.2', 			'conta'=> 'FORNECEDORES', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>63, 	'pai_id'=>62, 	'codigo'=> '2.1.2.001', 		'conta'=> 'FORNECEDORES', 							'alias'=> 'fornecedor', 			'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>64, 	'pai_id'=>63, 	'codigo'=> '2.1.2.001.0001', 	'conta'=> 'Fornecedor a Pagar', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> '' ]);
        PlanoConta::firstOrCreate(['id'=>116, 	'pai_id'=>58, 	'codigo'=> '2.1.3', 			'conta'=> 'OBRIGACOES TRIBUTARIAS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>117, 	'pai_id'=>116, 	'codigo'=> '2.1.3.001', 		'conta'=> 'IMPOSTOS/CONTRIB A RECOLHER', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>118, 	'pai_id'=>117, 	'codigo'=> '2.1.3.001.0001', 	'conta'=> 'Simples Nacional a Recolher', 				'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>119, 	'pai_id'=>58, 	'codigo'=> '2.1.4', 			'conta'=> 'OBRIGACOES TRABALHISTAS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>120, 	'pai_id'=>119, 	'codigo'=> '2.1.4.001', 		'conta'=> 'OBRIGACOES C/ PESSOAL', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>121, 	'pai_id'=>119, 	'codigo'=> '2.1.4.002', 		'conta'=> 'OBRIGACOES SOCIAIS', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>122, 	'pai_id'=>119, 	'codigo'=> '2.1.4.005', 		'conta'=> 'PROVISOES', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>123, 	'pai_id'=>122, 	'codigo'=> '2.1.4.005.0001', 	'conta'=> 'Simples Nacional a Recolher', 				'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>124, 	'pai_id'=>58, 	'codigo'=> '2.1.5', 			'conta'=> 'OUTRAS OBRIGACOES', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>125, 	'pai_id'=>124, 	'codigo'=> '2.1.5.001', 		'conta'=> 'CONTAS A PAGAR', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>126, 	'pai_id'=>125, 	'codigo'=> '2.1.5.001.0001', 	'conta'=> 'Servicos Contabeis', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>127, 	'pai_id'=>125, 	'codigo'=> '2.1.5.001.0002', 	'conta'=> 'Diferença de Aliquota SEFAZ-RN', 			'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>128, 	'pai_id'=>125, 	'codigo'=> '2.1.5.001.0003', 	'conta'=> 'DAM Doc Arrecadação Municipal', 			'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>129, 	'pai_id'=>125, 	'codigo'=> '2.1.5.001.0004', 	'conta'=> 'Energia Eletrica', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>130, 	'pai_id'=>57, 	'codigo'=> '2.2', 				'conta'=> 'PASSIVO NAO-CIRCULANTE', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>131, 	'pai_id'=>130, 	'codigo'=> '2.2.1', 			'conta'=> 'EXIGIVEL A LONGO PRAZO', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>132, 	'pai_id'=>131, 	'codigo'=> '2.2.1.001', 		'conta'=> 'EMPRESTIMOS', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>133, 	'pai_id'=>131, 	'codigo'=> '2.2.1.002', 		'conta'=> 'FINANCIAMENTOS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>134, 	'pai_id'=>131, 	'codigo'=> '2.2.1.003', 		'conta'=> 'FORNECEDORES', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>135, 	'pai_id'=>57, 	'codigo'=> '2.3', 				'conta'=> 'PATRIMONIO LIQUIDO', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>136, 	'pai_id'=>135, 	'codigo'=> '2.3.1', 			'conta'=> 'CAPITAL SOCIAL', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>137, 	'pai_id'=>136, 	'codigo'=> '2.3.1.001', 		'conta'=> 'CAPITAL INTEGRALIZADO', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>138, 	'pai_id'=>137, 	'codigo'=> '2.3.1.001.0001', 	'conta'=> 'Capital Integralizado', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>139, 	'pai_id'=>136, 	'codigo'=> '2.3.1.002', 		'conta'=> '(-) CAPITAL A INTEGRALIZAR', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>140, 	'pai_id'=>139, 	'codigo'=> '2.3.1.002.0001', 	'conta'=> '(-) Capital a Integralizar', 				'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>141, 	'pai_id'=>135, 	'codigo'=> '2.3.2', 			'conta'=> 'RESERVAS DE CAPITAL', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>142, 	'pai_id'=>135, 	'codigo'=> '2.3.3', 			'conta'=> 'RESERVAS DE REAVALIACAO', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>143, 	'pai_id'=>135, 	'codigo'=> '2.3.4', 			'conta'=> 'RESERVAS DE LUCROS', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>144, 	'pai_id'=>135, 	'codigo'=> '2.3.5', 			'conta'=> 'LUCROS OU PREJUIZOS ACUMULADOS', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>145, 	'pai_id'=>144, 	'codigo'=> '2.3.5.001', 		'conta'=> 'LUCROS OU PREJUIZOS ACUMULADOS', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>146, 	'pai_id'=>145, 	'codigo'=> '2.3.5.001.0001', 	'conta'=> 'Lucros Acumulados', 						'alias'=> 'lucro_acumulado', 		'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>147, 	'pai_id'=>145, 	'codigo'=> '2.3.5.001.0002', 	'conta'=> '(-) Prejuizos Acumulados', 				'alias'=> 'prejuizo_acumulado', 	'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>148, 	'pai_id'=>145, 	'codigo'=> '2.3.5.001.0003', 	'conta'=> 'Resultado do Exercicio em Curso', 			'alias'=> 'are',					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>149, 	'pai_id'=>NULL,	'codigo'=>  '3', 				'conta'=> 'RECEITAS', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>150, 	'pai_id'=>149, 	'codigo'=> '3.1', 				'conta'=> 'RECEITAS OPERACIONAIS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>151, 	'pai_id'=>150, 	'codigo'=> '3.1.1', 			'conta'=> 'RECEITAS BRUTAS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>152, 	'pai_id'=>151, 	'codigo'=> '3.1.1.001', 		'conta'=> 'RECEITAS BRUTAS S/ VENDAS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>153, 	'pai_id'=>152, 	'codigo'=> '3.1.1.001.0001', 	'conta'=> 'Venda de Mercadorias', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>154, 	'pai_id'=>151, 	'codigo'=> '3.1.1.002', 		'conta'=> 'RECEITAS BRUTAS S/ SERVICOS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>155, 	'pai_id'=>154, 	'codigo'=> '3.1.1.002.0001', 	'conta'=> 'Receitas s/ Serviços', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>156, 	'pai_id'=>150, 	'codigo'=> '3.1.2 (-)', 		'conta'=> 'DEDUCOES S/ RECEITA BRUTA', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>157, 	'pai_id'=>156, 	'codigo'=> '3.1.2.001', 		'conta'=> '(-) CANCELAMETNOS E DEVOLUCOES', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>158, 	'pai_id'=>156, 	'codigo'=> '3.1.2.002', 		'conta'=> '(-) DESCONTOS INCONDICIONAIS', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>159, 	'pai_id'=>156, 	'codigo'=> '3.1.2.003', 		'conta'=> '(-) IMPOSTOS S/ VENDAS E SERVICOS', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>160, 	'pai_id'=>159, 	'codigo'=> '3.1.2.003.0001', 	'conta'=> 'Simples Nacional', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>161, 	'pai_id'=>150, 	'codigo'=> '3.1.3', 			'conta'=> 'RECEITAS FINANCEIRAS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>162, 	'pai_id'=>161, 	'codigo'=> '3.1.3.001', 		'conta'=> 'JUROS E DESCONTOS', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>163, 	'pai_id'=>150, 	'codigo'=> '3.1.4', 			'conta'=> 'RECUPERACAO DE DESPESAS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>164, 	'pai_id'=>163, 	'codigo'=> '3.1.4.001', 		'conta'=> 'RECUP CRED-CONSID IRRECUPERAVEIS', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>165, 	'pai_id'=>150, 	'codigo'=> '3.1.5', 			'conta'=> 'OUTRAS RECEITAS OPERACIONAIS', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>166, 	'pai_id'=>165, 	'codigo'=> '3.1.5.001', 		'conta'=> 'RECEITAS DIVERSAS', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>167, 	'pai_id'=>149, 	'codigo'=> '3.2', 				'conta'=> 'RECEITAS NAO-OPERACIONAIS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>168, 	'pai_id'=>167, 	'codigo'=> '3.2.1', 			'conta'=> 'RESULTADOS NAO-OPERACIONAIS',	 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>169, 	'pai_id'=>168, 	'codigo'=> '3.2.1.001', 		'conta'=> 'RESULT POSITIVO ALIEN INVESTIMENTO', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>170, 	'pai_id'=>168, 	'codigo'=> '3.2.1.002', 		'conta'=> 'LUCROS ALIEN IMOBILIZADO', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>171, 	'pai_id'=>168, 	'codigo'=> '3.2.1.003', 		'conta'=> 'RESULTADO SINISTRO C/ IMOBILIZADO', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>172, 	'pai_id'=>NULL, 	'codigo'=> '4', 				'conta'=> 'DESPESAS', 								'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> '' ]);
        PlanoConta::firstOrCreate(['id'=>173, 	'pai_id'=>172, 	'codigo'=> '4.1', 				'conta'=> 'DESPESAS OPERACIONAIS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>174, 	'pai_id'=>173, 	'codigo'=> '4.1.1', 			'conta'=> 'DESPESAS C/ VENDAS', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>175, 	'pai_id'=>174, 	'codigo'=> '4.1.1.001', 		'conta'=> 'DESPESAS C/ PESSOAL', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>176, 	'pai_id'=>174, 	'codigo'=> '4.1.1.002', 		'conta'=> 'COMISSOES S/ VENDAS', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>177, 	'pai_id'=>174, 	'codigo'=> '4.1.1.003', 		'conta'=> 'PROPAGANDA E PUBLICIDADE', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>178, 	'pai_id'=>177, 	'codigo'=> '4.1.1.003.0001', 	'conta'=> 'Publicidade', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>179, 	'pai_id'=>177, 	'codigo'=> '4.1.1.003.0002', 	'conta'=> 'Patrocinios', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>180, 	'pai_id'=>177, 	'codigo'=> '4.1.1.003.0003', 	'conta'=> 'Amostra Gratis', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>181, 	'pai_id'=>174, 	'codigo'=> '4.1.1.004', 		'conta'=> 'DESPESAS C/ ENTREGA', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>182, 	'pai_id'=>181, 	'codigo'=> '4.1.1.004.0001', 	'conta'=> 'Fretes e Carretos', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>183, 	'pai_id'=>181, 	'codigo'=> '4.1.1.004.0002', 	'conta'=> 'Manutencao de Veiculos', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>184, 	'pai_id'=>181, 	'codigo'=> '4.1.1.004.0003', 	'conta'=> 'Combustiveis', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>185, 	'pai_id'=>174, 	'codigo'=> '4.1.1.005', 		'conta'=> 'DESPESAS C/ VIAGENS', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>186, 	'pai_id'=>174, 	'codigo'=> '4.1.1.006', 		'conta'=> 'DESPESAS GERAIS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>187, 	'pai_id'=>186, 	'codigo'=> '4.1.1.006.0001', 	'conta'=> 'Manutencao e Reparo', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>188, 	'pai_id'=>186, 	'codigo'=> '4.1.1.006.0003', 	'conta'=> 'Telefone', 								'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>189, 	'pai_id'=>186, 	'codigo'=> '4.1.1.006.0004', 	'conta'=> 'Celular', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>190, 	'pai_id'=>186, 	'codigo'=> '4.1.1.006.0005', 	'conta'=> 'Despesas Postais', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>191, 	'pai_id'=>186, 	'codigo'=> '4.1.1.006.0006', 	'conta'=> 'Servicos Prestados por Terceiros', 		'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>192, 	'pai_id'=>174, 	'codigo'=> '4.1.1.007', 		'conta'=> 'PERDAS NO RECEBIMENTO DE CREDITOS', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>193, 	'pai_id'=>173, 	'codigo'=> '4.1.2', 			'conta'=> 'DESPESAS ADMINISTRATIVAS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>194, 	'pai_id'=>193, 	'codigo'=> '4.1.2.001', 		'conta'=> 'DESPESAS C/ PESSOAL', 						'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>195, 	'pai_id'=>193, 	'codigo'=> '4.1.2.002', 		'conta'=> 'ALUGUEIS E ARRENDAMENTOS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>196, 	'pai_id'=>193, 	'codigo'=> '4.1.2.003', 		'conta'=> 'IMPOSTOS, TAXAS, CONTRIBUICOES', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>197, 	'pai_id'=>196, 	'codigo'=> '4.1.2.003.0001', 	'conta'=> 'IPTU', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>198, 	'pai_id'=>196, 	'codigo'=> '4.1.2.003.0002', 	'conta'=> 'IPVA', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>199, 	'pai_id'=>196, 	'codigo'=> '4.1.2.003.0005', 	'conta'=> 'Honorarios Contabeis', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>200, 	'pai_id'=>196, 	'codigo'=> '4.1.2.003.0006', 	'conta'=> 'Alvará', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>201, 	'pai_id'=>193, 	'codigo'=> '4.1.2.004', 		'conta'=> 'DESPESAS GERAIS', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>202, 	'pai_id'=>201, 	'codigo'=> '4.1.2.004.0001', 	'conta'=> 'Certificado Digital', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>203, 	'pai_id'=>201, 	'codigo'=> '4.1.2.004.0002', 	'conta'=> 'Energia Eletrica', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>204, 	'pai_id'=>201, 	'codigo'=> '4.1.2.004.0003', 	'conta'=> 'Agua e Esgoto', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>205, 	'pai_id'=>201, 	'codigo'=> '4.1.2.004.0004', 	'conta'=> 'Material de Escritorio', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>206, 	'pai_id'=>193, 	'codigo'=> '4.1.2.005', 		'conta'=> 'DESPESAS FINANCEIRAS', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>207, 	'pai_id'=>206, 	'codigo'=> '4.1.2.005.0001', 	'conta'=> 'Juros Bancarios', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>208, 	'pai_id'=>206, 	'codigo'=> '4.1.2.005.0002', 	'conta'=> 'Tarifas Bancarias', 						'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>209, 	'pai_id'=>193, 	'codigo'=> '4.1.2.006', 		'conta'=> 'DEPRECIAÇÕES', 							'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>210, 	'pai_id'=>209, 	'codigo'=> '4.1.2.006.0001', 	'conta'=> 'Juros de Mora', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>211, 	'pai_id'=>209, 	'codigo'=> '4.1.2.006.0002', 	'conta'=> 'Máquinas e Equipamentos', 					'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>212, 	'pai_id'=>209, 	'codigo'=> '4.1.2.006.0003', 	'conta'=> 'Diferença Aliquota SEFAZ-RN', 				'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>213, 	'pai_id'=>172, 	'codigo'=> '4.2', 				'conta'=> 'DESPESAS NAO-OPERACIONAIS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>214, 	'pai_id'=>213, 	'codigo'=> '4.2.1', 			'conta'=> 'RESULTADOS NAO-OPERACIONAIS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>215, 	'pai_id'=>214, 	'codigo'=> '4.2.1.001', 		'conta'=> 'OUTRAS BAIXAS DO ATIVO PERMANENTE', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>216, 	'pai_id'=>214, 	'codigo'=> '4.2.1.002', 		'conta'=> 'PERDAS', 									'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>217, 	'pai_id'=>216, 	'codigo'=> '4.3.1.002.0001', 	'conta'=> 'Perdas p/ Falta no Inventario', 			'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>218, 	'pai_id'=>172, 	'codigo'=> '4.3', 				'conta'=> 'CUSTOS C/ PRODUTOS/SERVICOS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>219, 	'pai_id'=>218, 	'codigo'=> '4.3.1', 			'conta'=> 'CUSTOS C/ PRODUTOS/SERVICOS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>220, 	'pai_id'=>219, 	'codigo'=> '4.3.1.001', 		'conta'=> 'CUSTOS C/ PRODUTOS VENCIDOS', 				'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>221, 	'pai_id'=>220, 	'codigo'=> '4.3.2', 			'conta'=> 'CUSTOS C/ SERVICOS PRESTADOS', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>222, 	'pai_id'=>221, 	'codigo'=> '4.3.2.001', 		'conta'=> 'CUSTOS C/ SERVICOS PRESTADOS', 			'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>223, 	'pai_id'=>218, 	'codigo'=> '4.3.3', 			'conta'=> 'CUSTOS C/ MERCADORIAS VENDIDAS CMV', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>224, 	'pai_id'=>223, 	'codigo'=> '4.3.3.001', 		'conta'=> 'CUSTOS C/ MERCADORIAS VENDIDAS CMV', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>225, 	'pai_id'=>224, 	'codigo'=> '4.3.3.001.0001', 	'conta'=> 'Custo com Mercadorias Vendidas', 			'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>226, 	'pai_id'=>NULL, 	'codigo'=> '5', 				'conta'=> 'CONTAS DE RESULTADOS DO EXERCICIO', 		'alias'=> '', 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>227, 	'pai_id'=>226, 	'codigo'=> '5.1', 				'conta'=> 'APURACAO DO RESULTADO DO EXERCICIO', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>228, 	'pai_id'=>227, 	'codigo'=> '5.1.1', 			'conta'=> 'APURACAO DO RESULTADO DE EXERCICIO', 		'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>229, 	'pai_id'=>228, 	'codigo'=> '5.1.1.001', 		'conta'=> 'Resultado do Exercicio', 					'alias'=> NULL, 					'tipo'=> 'S', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>230, 	'pai_id'=>229, 	'codigo'=> '5.1.1.001.0001', 	'conta'=> 'Apuração do Resultado do Exercício', 		'alias'=> 'are', 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>241, 	'pai_id'=>186, 	'codigo'=> '4.1.1.006.0007', 	'conta'=> 'Despesa de Organização', 					'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>242, 	'pai_id'=>195, 	'codigo'=> '4.1.2.002.0001', 	'conta'=> 'Aluguel Passivo', 							'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>243, 	'pai_id'=>158, 	'codigo'=> '3.1.2.002.0001', 	'conta'=> 'Descontos Obtidos', 						'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>244, 	'pai_id'=>158, 	'codigo'=> '3.1.2.002.0002', 	'conta'=> 'Juros Ativo', 								'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>245, 	'pai_id'=>120, 	'codigo'=> '2.1.4.001.0001', 	'conta'=> 'Salários a Pagar', 						'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>246, 	'pai_id'=>194, 	'codigo'=> '4.1.2.001.0001', 	'conta'=> 'Despesas com Salários', 					'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>247, 	'pai_id'=>125, 	'codigo'=> '2.1.5.001.0005', 	'conta'=> 'Contas a Pagar', 							'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>248, 	'pai_id'=>7, 		'codigo'=> '1.1.1.002.0001', 	'conta'=> 'Banco do Brasil', 							'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>249, 	'pai_id'=>10, 	'codigo'=> '1.1.2.001.0001', 	'conta'=> 'Manoel Jailton Sousa', 					'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>250, 	'pai_id'=>63, 	'codigo'=> '2.1.2.001.0002', 	'conta'=> 'mjailton Cursos', 							'alias'=> '', 					'tipo'=> 'A', 'natureza'=> 'C']);
        PlanoConta::firstOrCreate(['id'=>251, 	'pai_id'=>10, 	'codigo'=> '1.1.2.001.0002', 	'conta'=> 'teste', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>252, 	'pai_id'=>63, 	'codigo'=> '2.1.2.001.0003', 	'conta'=> 'teste', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);
        PlanoConta::firstOrCreate(['id'=>253, 	'pai_id'=>63, 	'codigo'=> '2.1.2.001.0004', 	'conta'=> 'Caema', 									'alias'=> NULL, 					'tipo'=> 'A', 'natureza'=> 'D']);

    }
}
